# _config_preset.toml

# ------------------------------------------------------------  IO / sampling
[io]
sample_rate    = 100_000   # Hz
gen_chunk_sec  = 0.1       # s  corresponds to PROC_INTERVAL up to 0.05
proc_interval  = 0.125     # s  process rate
queue_depth    = 40        # raw AB backlog
quad_depth     = 40        # processed backlog

# ------------------------------------------------------------  encoder postproc
[encoder_postproc]
quadpulse_width = 0.00025  # width [s] assuming 4x given 1 rps
threshold       = 2.5          # V logic threshold

# ------------------------------------------------------------  GUI
[gui]
plot_sec        = 0.15     # fixed x-axis window width [s] 1/(0.2*36) < 0.15, 1/(1*36) = 0.03 in 0.03 case pruning length might be too short
gui_interval_ms = 50       # GUI update interval [ms] e.g. 50ms=20Hz
display_sec     = 36_000   # 10 hour [s]
pruning         = 100      # pruning length [s]

# ------------------------------------------------------------  logging to h5
[logging]
log_chunk = 1024           # flush log queue every N data
log_data_num = 4           # number of data columns (t, com, vel, power)

# ------------------------------------------------------------  encoder
[debug_encoder]
pulse_height    = 5.0          # V
pulse_duty      = 0.5
pulse_phase_A   = 0.0          # phase delay for encoder A [s]
input_velocity  = 0.1          # rps

# ------------------------------------------------------------  power supply
[debug_power]
amplitude = 0.3                     # V
phase     = 0.0                     # rad